version: "3.8"

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"  # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,sqs,lambda,dynamodb,cloudwatch,apigateway,iam,sts,sns,firehose,es,kinesis,ses,sagemaker
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=0
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - ./localstack-volume:/var/lib/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock