services: 
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ../projects:/projects
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
  
  jenkins-agent1:
    image: jenkins/inbound-agent:latest
    container_name: jenkins-agent1
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=agent1-v2
      - JENKINS_SECRET=${JENKINS_SECRET_AGENT1}
    depends_on:
      - jenkins
  
  jenkins-agent2:
    build: ./agent-node-python
    container_name: jenkins-agent2
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=agent2-v2
      - JENKINS_SECRET=${JENKINS_SECRET_AGENT2}
    depends_on:
      - jenkins
    command: >
      sh -c "
        echo 'Waiting for Jenkins to be ready...';
        until curl --silent --head --fail $${JENKINS_URL}/login; do
          echo 'Jenkins is not ready yet... sleeping 5 seconds';
          sleep 5;
        done;
        echo 'Jenkins is up! Downloading agent.jar...';
        curl -o agent.jar $${JENKINS_URL}/jnlpJars/agent.jar &&
        java -jar agent.jar -jnlpUrl $${JENKINS_URL}/computer/$${JENKINS_AGENT_NAME}/slave-agent.jnlp -secret $${JENKINS_SECRET}
      "